language: cpp
sudo: required
dist: trusty
ddons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      - kalakris-cmake
    packages:
      - g++-6
      - cmake
env: 
compiler: gcc
install:
  - sudo ln -s /usr/bin/g++-6 /usr/bin/g++ -f
script:
  - cmake .
  - make
