language: cpp
sudo: required
dist: trusty
ddons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      - kalakris-cmake
    packages:
      - g++-6
      - cmake
env: COMILER=g++-6
compiler: gcc

script:
  - cmake .
  - make
