language: cpp
sudo: required
dist: trusty
ddons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      - kalakris-cmake
    packages:
      - gcc-6
      - g++-6
      - cmake
env: 
compiler: gcc
install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
script:
  - cmake .
  - make
